version: "3.8"

services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongo
      - sqlserver
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    restart: always
    environment:
      SA_PASSWORD: "YourStrongPassword"
      ACCEPT_EULA: "Y"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
